EtnaShopWeb/EtnaShopWeb/Controllers/OrderController.cs
using EtnaShop.DataAccess.Repository.IRepository;
using EtnaShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace EtnaShopWeb.Controllers
{
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<ShoppingCart> listCart;
            listCart = _unitOfWork.ShoppingCart.GetAll();
            return View(listCart);
        }


        public IActionResult Details(string orderId)
        {
            IEnumerable<ShoppingCart> listCart;
            listCart = _unitOfWork.ShoppingCart.GetAll(x => x.OrderId==orderId, includeProp: "Product");
            double total = 0;
            List<double> subTotalsList = new List<double>();
            foreach (ShoppingCart cart in listCart)
            {
                subTotalsList.Add(cart.Count * cart.Product.Price);
                total += cart.Count * cart.Product.Price;
            }
            ViewBag.SubTotals = subTotalsList;
            ViewBag.Total = total;
            ViewBag.OrderId=orderId;
            
            return View(listCart);
        }
    }
}

EtnaShopWeb/EtnaShopWeb/Views/Order/Details.cshtml
@using EtnaShop.Models;
@model IEnumerable<ShoppingCart>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Orden: @ViewBag.OrderId.ToString()</h2>
        </div> 
        </div>
    <br/><br/>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Cantidad / Precio</th>
      <th scope="col">Subtotal </th>
    </tr>
  </thead>
    <tbody>
            @{
                int i = 0;
                @foreach(var obj in Model)
                 {
                    <tr class="table-active">
                        <td width=50%>
                            @obj.Product.Name
                        </td>
                        <td width=30%>
                            @obj.Count&nbsp;x&nbsp;$@obj.Product.Price
                        </td>
                        <td width=10%>
                            @ViewBag.SubTotals[i++].ToString("c")
                        </td>
                    </tr>
                 }
            }
                
      </tbody>
</table>
<hr />
<div class="col-12 text-end">
    <h2><strong class="text-info">Total:&nbsp;@ViewBag.Total.ToString("c")</strong></h2>
</div>
<br/>
<div class="col-12 text-end">
    <a asp-controller="Order" asp-action="Index" class="btn btn-secondary"  style="width:180px">
            Volver
        </a>
</div>
</div>

EtnaShopWeb/EtnaShopWeb/Views/Order/Index.cshtml
@using EtnaShop.Models;
@model IEnumerable<ShoppingCart>

@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Ordenes</h2>
        </div> 
        
    </div>
    <br/><br/>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nro de Orden</th>
      </tr>
  </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr class="table-active">
                <td scope="row" width=50%>
                   <strong>@obj.OrderId</strong>
                </td>
                <td>
                    <div class="text-end" role="group">
                        <a asp-controller="Order" asp-action="Details" asp-route-orderId="@obj.OrderId" asp-route-close="true" class="btn btn-primary">
                            Ver Detalles
                        </a>
                        
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br/>
<div class="col-12 text-end">
    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary"  style="width:180px">
            Volver
        </a>
</div>
</div>