EtnaShopWeb/EtnaShopWeb/Controllers/CartController.cs
using EtnaShop.DataAccess.Repository.IRepository;
using EtnaShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace EtnaShopWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            string orderId = HttpContext.Request.Cookies["order_id"];
            IEnumerable<ShoppingCart> listCart;
            listCart = _unitOfWork.ShoppingCart.GetAll(x=>x.OrderId==orderId, includeProp: "Product");
            double total=0;
            List<double> subTotalsList = new List<double>();
            foreach(ShoppingCart cart in listCart)
            {
                subTotalsList.Add(cart.Count * cart.Product.Price);
                total += cart.Count * cart.Product.Price;
            }
            ViewBag.SubTotals = subTotalsList;
            ViewBag.Total=total;
            ViewBag.OrderId = orderId;
            return View(listCart);
        }

        
        public IActionResult Delete(int? id)
        {
            var cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(x => x.Id == id);
            if (cartFromDb == null)
            {
                return NotFound();
            }
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction("Index");


        }

        public IActionResult Details(string orderId)
        {
            IEnumerable<ShoppingCart> listCart;
            listCart = _unitOfWork.ShoppingCart.GetAll(x => x.OrderId == orderId, includeProp: "Product");
            double total = 0;
            List<double> subTotalsList = new List<double>();
            foreach (ShoppingCart cart in listCart)
            {
                subTotalsList.Add(cart.Count * cart.Product.Price);
                total += cart.Count * cart.Product.Price;
            }
            ViewBag.SubTotals = subTotalsList;
            ViewBag.Total = total;
            ViewBag.OrderId = orderId;
            string cookieValue = Guid.NewGuid().ToString();
            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Now.AddDays(3);
            HttpContext.Response.Cookies.Append("order_id", cookieValue, cookieOptions);
            return View(listCart);
        }


    }
}

EtnaShopWeb/EtnaShopWeb/Controllers/ShoppingCartController.cs
using EtnaShop.DataAccess.Repository.IRepository;
using EtnaShop.Models;
using EtnaShopWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace EtnaShopWeb.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        
        public ShoppingCartController(IUnitOfWork unitOfwork)
        {
            _unitOfWork = unitOfwork;
            
            
        }

        public IActionResult Index()
        {
            if (!HttpContext.Request.Cookies.ContainsKey("order_id"))
            {
                string cookieValue = Guid.NewGuid().ToString();
                CookieOptions cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(3);
                HttpContext.Response.Cookies.Append("order_id", cookieValue, cookieOptions);
            }
            IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll();
            return View(objProductList);
        }
       
       

        //Get
        public IActionResult Details(int productId)
        {
            ShoppingCart cart;
            Product product = _unitOfWork.Product.GetFirstOrDefault(x=>x.Id
            == productId);
            
           
                cart = new()
                {
                    Count = 1,
                    ProductId = productId,
                    Product = product,
                    OrderId = HttpContext.Request.Cookies["order_id"].ToString()
                };

           
            return View(cart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ShoppingCart cart)
        {
                _unitOfWork.ShoppingCart.Add(cart);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            
            
        }
    }
}

EtnaShopWeb/EtnaShopWeb/Views/Cart/Details.cshtml
@using EtnaShop.Models;
@model IEnumerable<ShoppingCart>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Orden: @ViewBag.OrderId.ToString()</h2>
        </div> 
        </div>
    <br/><br/>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Cantidad / Precio</th>
      <th scope="col">Subtotal </th>
    </tr>
  </thead>
    <tbody>
            @{
                int i = 0;
                @foreach(var obj in Model)
                 {
                    <tr class="table-active">
                        <td width=50%>
                            @obj.Product.Name
                        </td>
                        <td width=30%>
                            @obj.Count&nbsp;x&nbsp;$@obj.Product.Price
                        </td>
                        <td width=10%>
                            @ViewBag.SubTotals[i++].ToString("c")
                        </td>
                    </tr>
                 }
            }
                
      </tbody>
</table>
<hr />
<div class="col-12 text-end">
    <h2><strong class="text-info">Total:&nbsp;@ViewBag.Total.ToString("c")</strong></h2>
</div>
<br/>
<div class="col-12 text-end">
    <a asp-controller="Cart" asp-action="Index" class="btn btn-secondary"  style="width:180px">
            Volver
        </a>
</div>
</div>

EtnaShopWeb/EtnaShopWeb/Views/Cart/Index.cshtml
@using EtnaShop.Models;
@model IEnumerable<ShoppingCart>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Carrito de Compras</h2>
        </div> 
        </div>
    <br/><br/>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Cantidad / Precio</th>
      <th scope="col">Subtotal </th>
    </tr>
  </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr class="table-active">
                <td width=50%>
                    @obj.Product.Name
                </td>
                <td width=30%>
                    @obj.Count&nbsp;x&nbsp;$@obj.Product.Price
                </td>
                <td width=10%>
                   @ViewBag.SubTotals[0].ToString("c")
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                       <a asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger">
                            <i class="bi bi-trash3-fill"></i>Borrar
                        </a>
                    </div>
                </td>
            </tr>
        }
      </tbody>
</table>
<hr />
<div class="col-12 text-end">
    <h2><strong class="text-info">Total:&nbsp;@ViewBag.Total.ToString("c")</strong></h2>
</div>
<br/>
<div class="col-12 text-end">
    <a asp-controller="ShoppingCart" asp-action="Index" class="btn btn-secondary"  style="width:180px">
            Volver
        </a>
        <a asp-controller="Cart" asp-action="Details" asp-route-orderId="@ViewBag.OrderId" class="btn btn-warning"  style="width:180px">
            Finalizar
        </a>
</div>
</div>